INSERT INTO Cuisines (name, CreatedBy, Created, LastModifiedBy ,LastModified, Description)
VALUES 
('American', null, GETDATE(), null, GETDATE(), 'Cuisine of the United States'),
('Chinese', null, GETDATE(), null, GETDATE(), 'Traditional cuisine of China'),
('French', null, GETDATE(), null, GETDATE(), 'Cuisine of France'),
('Indian', null, GETDATE(), null, GETDATE(), 'Cuisine of India'),
('Italian', null, GETDATE(), null, GETDATE(), 'Cuisine of Italy'),
('Japanese', null, GETDATE(), null, GETDATE(), 'Cuisine of Japan'),
('Korean', null, GETDATE(), null, GETDATE(), 'Cuisine of Korea'),
('Mexican', null, GETDATE(), null, GETDATE(), 'Cuisine of Mexico'),
('Spanish', null, GETDATE(), null, GETDATE(), 'Cuisine of Spain'),
('Thai', null, GETDATE(), null, GETDATE(), 'Cuisine of Thailand'),
('Vietnamese', null, GETDATE(), null, GETDATE(), 'Cuisine of Vietnam'),
('Greek', null, GETDATE(), null, GETDATE(), 'Cuisine of Greece'),
('Lebanese', null, GETDATE(), null, GETDATE(), 'Cuisine of Lebanon'),
('Armenian', null, GETDATE(), null, GETDATE(), 'Cuisine of Armenia'),
('Moroccan', null, GETDATE(), null, GETDATE(), 'Cuisine of Morocco'),
('Peruvian', null, GETDATE(), null, GETDATE(), 'Cuisine of Peru'),
('Brazilian', null, GETDATE(), null, GETDATE(), 'Cuisine of Brazil'),
('Argentinian', null, GETDATE(), null, GETDATE(), 'Cuisine of Argentina'),
('Russian', null, GETDATE(), null, GETDATE(), 'Cuisine of Russia'),
('German', null, GETDATE(), null, GETDATE(), 'Cuisine of Germany'),
('Swedish', null, GETDATE(), null, GETDATE(), 'Cuisine of Sweden'),
('African', null, GETDATE(), null, GETDATE(), 'Cuisine of Africa'),
('Caribbean', null, GETDATE(), null, GETDATE(), 'Cuisine of the Caribbean'),
('Mediterranean', null, GETDATE(), null, GETDATE(), 'Cuisine of the Mediterranean region'),
('Middle Eastern', null, GETDATE(), null, GETDATE(), 'Cuisine of the Middle East');